ALTER TABLE clientes DROP COLUMN plano_id;

ALTER TABLE clientes ADD COLUMN data_cadastro TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE clientes ADD COLUMN data_atualizacao TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE planos ADD COLUMN data_cadastro TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE planos ADD COLUMN data_atualizacao TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE assinaturas ADD COLUMN data_cadastro TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE assinaturas ADD COLUMN data_atualizacao TIMESTAMP NOT NULL DEFAULT NOW();
