ALTER TABLE clientes
ALTER COLUMN data_cadastro TYPE TIMESTAMPTZ,
ALTER COLUMN data_atualizacao TYPE TIMESTAMPTZ;

ALTER TABLE planos
ALTER COLUMN data_cadastro TYPE TIMESTAMPTZ,
ALTER COLUMN data_atualizacao TYPE TIMESTAMPTZ;

ALTER TABLE assinaturas
ALTER COLUMN data_cadastro TYPE TIMESTAMPTZ,
ALTER COLUMN data_atualizacao TYPE TIMESTAMPTZ;